# -*- coding: utf-8 -*-
"""Bitcoin

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dZMcEOvWsrSDVguPvJSADBGvSqudxndT
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt


# %matplotlib inline

"""To read the memepool.csv file and get the data of it."""

df =  pd.read_csv('/content/memepool.csv')
print(df.get)
df.head()

"""To print  the data of parent ids """

# Reading an excel file using Python
import xlrd

# Give the location of the file
loc = ("/content/memepool.xlsx")

# To open Workbook
wb = xlrd.open_workbook(loc)
sheet = wb.sheet_by_index(0)

# For row 0 and column 0
for i in range(sheet.nrows):
    print(sheet.cell_value(i,3))

"""To get the weight """

# Reading an excel file using Python
import xlrd

# Give the location of the file
loc = ("/content/memepool.xlsx")

# To open Workbook
wb = xlrd.open_workbook(loc)
sheet = wb.sheet_by_index(0)

# For row 0 and column 0
for i in range(sheet.nrows):
    print(sheet.cell_value(i,2))

"""To get the fee"""

# Reading an excel file using Python
import xlrd

# Give the location of the file
loc = ("/content/memepool.xlsx")

# To open Workbook
wb = xlrd.open_workbook(loc)
sheet = wb.sheet_by_index(0)

# For row 0 and column 0
for i in range(sheet.nrows):
    print(sheet.cell_value(i,1))

"""To get the text ids"""

# Reading an excel file using Python
import xlrd

# Give the location of the file
loc = ("/content/memepool.xlsx")

# To open Workbook
wb = xlrd.open_workbook(loc)
sheet = wb.sheet_by_index(0)

# For row 0 and column 0
for i in range(sheet.nrows):
    print(sheet.cell_value(i,0))

class  MempoolTransaction():
  def init (self, txid, fee, weight, parents):
   self.txid  =  txid
   self.fee  =  int(fee)
#  TODO:  add  code  to  parse  weight  and  parents  fields
  def parse_memepool_csv():
    df =  pd.read_csv('/content/memepool.csv')
    print(df.get)
    df.head()


    with  open('mempool.csv')  as  f:
     return([MempoolTransaction(*line.strip().split(','))  for  line  in  f.readlines